before:
  hooks:
  - go mod tidy
builds:
- env:
    - CGO_ENABLED=0
  goos:
  - linux
  - windows
  - darwin
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
nfpms:
- license: Apache 2.0
  maintainer: Mikael Vandmo
  homepage: https://github.com/vandmo/hju
  bindir: /usr/bin
  dependencies:
  - git
  description: Tool for managing a set of repositories in a parent repository.
  formats:
  - deb
  - rpm
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
