name: Tests
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Set up Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Check out code
      uses: actions/checkout@v2

    - name: Generate internal/buildinfo.go
      uses: actions/github-script@v4
      with:
        script: |
          const fs = require('fs')
          const now = new Date()
          let buildinfo = ''
          buildinfo += 'package internal\n\n'
          buildinfo += 'const (\n'
          buildinfo += '\t'+`version = "${context.ref}"`+'\n'
          buildinfo += '\t'+`date    = "${now.toISOString()}"`+'\n'
          buildinfo += '\t'+`builder = "${context.actor}"`+'\n'
          buildinfo += '\t'+`commit  = "${context.sha}"`+'\n'
          buildinfo += ')\n'
          fs.writeFileSync('internal/buildinfo.go', buildinfo)

    - name: Inspect internal/buildinfo.go
      run: cat internal/buildinfo.go

    - name: Download dependencies
      run: go mod download

    - name: Build
      run: go build .
