name: Release

on:
  push:
    tags:
    - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        distribution: goreleaser
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Publish .deb and .rpm to Gemfury
      env:
        GEMFURY_PUSH_TOKEN: ${{ secrets.GEMFURY_PUSH_TOKEN }}
      run: |
        curl --form package=@dist/hju*_linux_386.deb https://{$GEMFURY_PUSH_TOKEN}@push.fury.io/bztk/
        curl --form package=@dist/hju*_linux_amd64.deb https://{$GEMFURY_PUSH_TOKEN}@push.fury.io/bztk/
        curl --form package=@dist/hju*_linux_arm64.deb https://{$GEMFURY_PUSH_TOKEN}@push.fury.io/bztk/
        curl --form package=@dist/hju*__linux_386.rpm https://{$GEMFURY_PUSH_TOKEN}@push.fury.io/bztk/
        curl --form package=@dist/hju*_linux_amd64.rpm https://{$GEMFURY_PUSH_TOKEN}@push.fury.io/bztk/
        curl --form package=@dist/hju*_linux_arm64.rpm https://{$GEMFURY_PUSH_TOKEN}@push.fury.io/bztk/
